[tool.poetry]
name = "python-eemi"
version = "0.1.0"
description = ""
authors = ["anthonyvouin <72597812+anthonyvouin@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.30.1"}
pydantic = "^2.7.4"
python-jose = "^3.3.0"
passlib = "^1.7.4"
<<<<<<< Updated upstream
bcrypt = "^4.1.3"
=======
pytest = "^8.2.2"
requests = "^2.32.3"
>>>>>>> Stashed changes


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
