[tool.poetry]
name = "python-eemi"
version = "0.1.0"
description = ""
authors = ["anthonyvouin <72597812+anthonyvouin@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
